### ISSUE TITLE
Issue with MarkDuplicates on Irma

### ISSUE THREAD

**Issue by MaxUlysse** [SciLifeLab/Sarek#496]
I think it might be a memory issue.

```
  INFO	2017-11-16 05:15:51	MarkDuplicates	Tracking 4429255 as yet unmatched pairs. 8549 records in RAM.
  INFO	2017-11-16 05:15:56	MarkDuplicates	Read   292,000,000 records.  Elapsed time: 00:26:01s.  Time for last 1,000,000:    5s.  Last read position: chr2:239,546,858
  INFO	2017-11-16 05:15:56	MarkDuplicates	Tracking 4437202 as yet unmatched pairs. 6208 records in RAM.
  INFO	2017-11-16 05:15:59	MarkDuplicates	Read   293,000,000 records.  Elapsed time: 00:26:04s.  Time for last 1,000,000:    3s.  Last read position: chr2:241,149,792
  INFO	2017-11-16 05:15:59	MarkDuplicates	Tracking 4443362 as yet unmatched pairs. 2907 records in RAM.
  INFO	2017-11-16 05:16:09	MarkDuplicates	Read   294,000,000 records.  Elapsed time: 00:26:14s.  Time for last 1,000,000:    9s.  Last read position: chr3:647,591
  INFO	2017-11-16 05:16:09	MarkDuplicates	Tracking 4451717 as yet unmatched pairs. 283037 records in RAM.
  INFO	2017-11-16 05:16:13	MarkDuplicates	Read   295,000,000 records.  Elapsed time: 00:26:17s.  Time for last 1,000,000:    3s.  Last read position: chr3:2,512,749
  INFO	2017-11-16 05:16:13	MarkDuplicates	Tracking 4460591 as yet unmatched pairs. 281629 records in RAM.
  INFO	2017-11-16 05:16:16	MarkDuplicates	Read   296,000,000 records.  Elapsed time: 00:26:21s.  Time for last 1,000,000:    3s.  Last read position: chr3:4,286,988
  INFO	2017-11-16 05:16:16	MarkDuplicates	Tracking 4469217 as yet unmatched pairs. 280085 records in RAM.
  INFO	2017-11-16 05:16:23	MarkDuplicates	Read   297,000,000 records.  Elapsed time: 00:26:28s.  Time for last 1,000,000:    6s.  Last read position: chr3:6,009,819
  INFO	2017-11-16 05:16:23	MarkDuplicates	Tracking 4478151 as yet unmatched pairs. 278597 records in RAM.
  INFO	2017-11-16 05:16:27	MarkDuplicates	Read   298,000,000 records.  Elapsed time: 00:26:32s.  Time for last 1,000,000:    3s.  Last read position: chr3:7,849,852
  INFO	2017-11-16 05:16:27	MarkDuplicates	Tracking 4486796 as yet unmatched pairs. 276984 records in RAM.
  INFO	2017-11-16 05:16:30	MarkDuplicates	Read   299,000,000 records.  Elapsed time: 00:26:35s.  Time for last 1,000,000:    3s.  Last read position: chr3:9,566,821
  INFO	2017-11-16 05:16:30	MarkDuplicates	Tracking 4495136 as yet unmatched pairs. 275485 records in RAM.
  INFO	2017-11-16 05:16:34	MarkDuplicates	Read   300,000,000 records.  Elapsed time: 00:26:39s.  Time for last 1,000,000:    3s.  Last read position: chr3:11,206,261
  INFO	2017-11-16 05:16:34	MarkDuplicates	Tracking 4503675 as yet unmatched pairs. 273631 records in RAM.
  INFO	2017-11-16 05:16:40	MarkDuplicates	Read   301,000,000 records.  Elapsed time: 00:26:44s.  Time for last 1,000,000:    5s.  Last read position: chr3:12,873,217
  INFO	2017-11-16 05:16:40	MarkDuplicates	Tracking 4513373 as yet unmatched pairs. 271808 records in RAM.
  INFO	2017-11-16 05:16:43	MarkDuplicates	Read   302,000,000 records.  Elapsed time: 00:26:48s.  Time for last 1,000,000:    3s.  Last read position: chr3:14,503,455
  INFO	2017-11-16 05:16:43	MarkDuplicates	Tracking 4520665 as yet unmatched pairs. 270192 records in RAM.
  INFO	2017-11-16 05:16:47	MarkDuplicates	Read   303,000,000 records.  Elapsed time: 00:26:52s.  Time for last 1,000,000:    3s.  Last read position: chr3:16,177,421
  INFO	2017-11-16 05:16:47	MarkDuplicates	Tracking 4529105 as yet unmatched pairs. 268569 records in RAM.
  INFO	2017-11-16 05:16:51	MarkDuplicates	Read   304,000,000 records.  Elapsed time: 00:26:56s.  Time for last 1,000,000:    4s.  Last read position: chr3:17,958,653
  INFO	2017-11-16 05:16:51	MarkDuplicates	Tracking 4537590 as yet unmatched pairs. 266942 records in RAM.
  [Thu Nov 16 05:16:51 UTC 2017] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 26.99 minutes.
  Runtime.totalMemory()=42520281088
  To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
  Exception in thread "main" picard.PicardException: Exception writing ReadEnds to file.
  	at picard.sam.markduplicates.util.ReadEndsForMarkDuplicatesCodec.encode(ReadEndsForMarkDuplicatesCodec.java:73)
  	at picard.sam.markduplicates.util.DiskBasedReadEndsForMarkDuplicatesMap$Codec.encode(DiskBasedReadEndsForMarkDuplicatesMap.java:104)
  	at picard.sam.markduplicates.util.DiskBasedReadEndsForMarkDuplicatesMap$Codec.encode(DiskBasedReadEndsForMarkDuplicatesMap.java:76)
  	at htsjdk.samtools.CoordinateSortedPairInfoMap.put(CoordinateSortedPairInfoMap.java:166)
  	at picard.sam.markduplicates.util.DiskBasedReadEndsForMarkDuplicatesMap.put(DiskBasedReadEndsForMarkDuplicatesMap.java:65)
  	at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:333)
  	at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:139)
  	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:209)
  	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
  	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
  Caused by: java.io.IOException: Cannot allocate memory
  	at java.io.FileOutputStream.writeBytes(Native Method)
  	at java.io.FileOutputStream.write(FileOutputStream.java:326)
  	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
  	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:95)
  	at java.io.DataOutputStream.writeInt(DataOutputStream.java:199)
  	at picard.sam.markduplicates.util.ReadEndsForMarkDuplicatesCodec.encode(ReadEndsForMarkDuplicatesCodec.java:58)
  	... 9 more
  .command.run.1: line 12: ps: command not found
```

**Comment by MaxUlysse** [comment]
cc @parlundin

**Comment by szilvajuhos** [comment]
Changed config, see how it goes (launched, still working)

**Comment by szilvajuhos** [comment]
It is a particularly nasty sample with high duplicates. Config changed on irma at /lupus/proj/ngi2016003/nobackup/perlu/CAW/configuration/uppmax-slurm.config

**Comment by MaxUlysse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix issue with MarkDuplicates on Irma](https://trello.com/c/GgMJWA1p/13-fix-issue-with-markduplicates-on-irma)

**Comment by MaxUlysse** [comment]
Increase memory for deep sequencing.
