### ISSUE TITLE
Failed to publish QC file - invalid cross-device link

### ISSUE THREAD

**Issue by szilvajuhos** [SciLifeLab/Sarek#581]
WARN: Failed to publish file: /scratch/83/04e6cc308bd27eb0b846c8d2821d86/MB2_SWID_N.recal.bam.samtools.stats.out; to: /lupus/proj/ngi2016004/private/szilva/ICGC/somatic/Somatic/Reports/SamToolsStats/MB2_SWID_N.recal.bam.samtools.stats.out [link] -- See log file for details
WARN: Failed to publish file: /scratch/d7/ad03aff16044d2a28603c2279837fd/MB2_SWID_T.recal.bam.samtools.stats.out; to: /lupus/proj/ngi2016004/private/szilva/ICGC/somatic/Somatic/Reports/SamToolsStats/MB2_SWID_T.recal.bam.samtools.stats.out [link] -- See log file for details

And the log shows:

`May-03 15:07:12.853 [Task monitor] WARN  nextflow.processor.PublishDir - Failed to publish file: /scratch/d7/ad03aff16044d2a28603c2279837fd/MB2_SWID_T.recal.bam.samtools.stats.out; to: /lupus/proj/ngi2016004/private/szilva/ICGC/somatic/Somatic/Reports/SamToolsStats/MB2_SWID_T.recal.bam.samtools.stats.out [link] -- See log file for details
java.nio.file.FileSystemException: /lupus/proj/ngi2016004/private/szilva/ICGC/somatic/Somatic/Reports/SamToolsStats/MB2_SWID_T.recal.bam.samtools.stats.out -> /scratch/d7/ad03aff16044d2a28603c2279837fd/MB2_SWID_T.recal.bam.samtools.stats.out: Invalid cross-device link
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixFileSystemProvider.createLink(UnixFileSystemProvider.java:476)
        at java.nio.file.Files.createLink(Files.java:1086)
        at java_nio_file_Files$createLink$4.call(Unknown Source)
`
My feeling is that by using /scratch on the node we are trying to link results to the NAS (lupus) in this case. Command line was for the slurm job:
`/lupus/proj/ngi2016004/private/szilva/nextflow/bin/nextflow run /lupus/proj/ngi2016004/pipelines/SciLifeLab/sarek/default/somaticVC.nf --project ngi2016004 --sample Preprocessing
/Recalibrated/recalibrated.tsv --tools mutect2,strelka --outDir Somatic -with-report somatic_2018-May-03-0957.report.html --containerPath /lupus/proj/ngi2016004/pipelines/SciLifeLab/sarek/containers --genome GRCh38 --genome_base /sw/data/uppnex/ToolBox/hg38bundle -profile singularityPath
`

**Comment by szilvajuhos** [comment]
Maybe we should have less versions and a unit test framework for all the stuff, as Travis has no slurm.

**Comment by MaxUlysse** [comment]
I'm not sure I follow what you want to do.

**Comment by MaxUlysse** [comment]
Closing due to inactivity and moving to [nf-core/sarek](https://github.com/nf-core/sarek/)
